### ISSUE TITLE
autoDrillDown ignores files in subdirectories

### ISSUE THREAD

**Issue by kaloyan-dev** [lachezarov/Sunrays-Theme#1]
The **autoDrillDown** feature of this otherwise exceptionally beautiful theme seems to ignore any files (that are not directories) when checking if it should "drill down".

Is that intended ? And if so, could there be a config option for modifying this behavior so that subdirectories that have files in them are not skipped ?

**Comment by lachezarov** [comment]
Thank you for the kind words.

The behavior is not intended, so I will add an option in the config later today.
